# frozen_string_literal: true

require './Constants/DeliverableConstants'
require './Constants/Constants'
require './Constants/Environments'
require './Managers/MatchManager'
require './Managers/TestManager'
require './Managers/BuildManager'
require './Managers/DistributionManager'
require './Managers/VersioningManager'

test_manager = TestManager.new(
  fastlane: self,
  device: Constants.DEVICE,
  output_directory: Constants.TEST_OUTPUT_DIRECTORY_PATH
)

match_manager = MatchManager.new(
  fastlane: self,
  keychain_name: Constants.KEYCHAIN_NAME,
  keychain_password: Constants.KEYCHAIN_PASSWORD,
  is_ci: Environments.CI
)

builder = BuildManager.new(fastlane: self)

distribution_manager = DistributionManager.new(
  fastlane: self,
  build_path: Constants.BUILD_PATH,
  firebase_token: Environments.FIREBASE_TOKEN
)

versioning_manager = VersioningManager.new(
  fastlane: self,
  project_path: Constants.PROJECT_PATH,
  main_target_name: Constants.MAIN_TARGET_NAME
)

before_all do
  ensure_bundle_exec
end

default_platform(:ios)

platform :ios do

  desc 'Build and Test'
  lane :build_and_test do
    test_manager.build_and_test(
      scheme: Constants.TESTS_SCHEME,
      targets: [Constants.TESTS_TARGET]
    )
  end

  # Code Sign

  desc 'Sync Development match signing'
  lane :sync_development_signing do
      match_manager.sync_development_signing(
        app_identifier: [
          Constants.BUNDLE_ID_STAGING,
          Constants.BUNDLE_ID_PRODUCTION
        ]
      )
  end

  desc 'Sync Adhoc match signing'
  lane :sync_adhoc_signing do
    match_manager.sync_adhoc_signing(app_identifier: [Constants.BUNDLE_ID_STAGING])
  end

  desc 'Sync Adhoc Production match signing'
  lane :sync_adhoc_production_signing do
    match_manager.sync_adhoc_signing(app_identifier: [Constants.BUNDLE_ID_PRODUCTION])
  end

  desc 'Sync AppStore match signing'
  lane :sync_appstore_signing do
    match_manager.sync_app_store_signing(app_identifier: [Constants.BUNDLE_ID_PRODUCTION])
  end

  desc 'Build and upload staging app to Firebase'
  lane :build_and_upload_staging_app do
    set_app_version
    bump_build
    builder.build_ad_hoc(
      Constants.SCHEME_NAME_STAGING,
      Constants.PRODUCT_NAME_STAGING,
      Constants.BUNDLE_ID_STAGING
    )
    upload_build_to_firebase(
      product_name: Constants.PRODUCT_NAME_STAGING,
      firebase_app_id: DeliverableConstants.FIREBASE_APP_ID_STAGING,
      tester_groups: DeliverableConstants.FIREBASE_TESTER_GROUPS
    )
    upload_build_dsym_to_firebase(
      product_name: Constants.PRODUCT_NAME_STAGING,
      gsp_name: DeliverableConstants.GSP_STAGING
    )
  end

  desc 'Build and upload Production app to Firebase'
  lane :build_and_upload_production_app do
    set_app_version
    bump_build
    builder.build_ad_hoc(
      Constants.SCHEME_NAME_PRODUCTION,
      Constants.PRODUCT_NAME_PRODUCTION,
      Constants.BUNDLE_ID_PRODUCTION
    )
    upload_build_to_firebase(
      product_name: Constants.PRODUCT_NAME_PRODUCTION,
      firebase_app_id: DeliverableConstants.FIREBASE_APP_ID_PRODUCTION,
      tester_groups: DeliverableConstants.FIREBASE_TESTER_GROUPS
    )
  end

  desc 'Register new devices'
  lane :register_new_device do
    device_name = prompt(text: 'Enter the device name: ')
    device_udid = prompt(text: 'Enter the device UDID: ')
    device_hash = {}
    device_hash[device_name] = device_udid
    register_devices(devices: device_hash)

    match_manager.sync_development_signing(app_identifier: nil, force: true)
    match_manager.sync_adhoc_signing(app_identifier: nil, force: true)
  end

  # Utilities

  desc 'Clean up derived data'
  lane :clean_up do
    clear_derived_data(derived_data_path: Constants.DERIVED_DATA_PATH)
  end

  desc 'check if any specific version number in build environment'
  private_lane :set_app_version do
    # Set up env var MANUAL_VERSION if we need to override the version number
    if (Environments.MANUAL_VERSION || '') != ''
      increment_version_number(
          version_number: Environments.MANUAL_VERSION
      )
    end
  end

  desc 'set build number with number of commits'
  private_lane :bump_build do
    increment_build_number(
      build_number: number_of_commits,
      xcodeproj: Constants.PROJECT_PATH
    )
  end

  desc 'upload build to Firebase app distribution'
  private_lane :upload_build_to_firebase do |options|
    release_notes = "#{options[:product_name]} #{versioning_manager.version_and_build_number}"
    distribution_manager.upload_to_firebase(
      product_name: options[:product_name],
      firebase_app_id: options[:firebase_app_id],
      tester_groups: options[:tester_groups],
      notes: release_notes
    )
  end
end
