name: Android & Shared - Lint and Test

on:
  pull_request:
    types: [ opened, reopened, edited, synchronize, ready_for_review ]

jobs:
  lint_and_test:
    name: Pull request review for Android & Shared
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Konfig Properties
        env:
          BUILD_KONFIG: ${{ secrets.BUILD_KONFIG }}
        run: |
          echo "$BUILD_KONFIG" > buildSrc/src/main/kotlin/appPackage/BuildKonfig.kt

      - name: Setup Google Services
        env:
          GOOGLE_SERVICES_JSON_STAGING: ${{ secrets.GOOGLE_SERVICES_JSON_STAGING }}
        run: |
          mkdir -p android/src/staging
          echo "$GOOGLE_SERVICES_JSON_STAGING" > android/src/staging/google-services.json

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Run unit tests with Kover
        run: ./gradlew koverMergedXmlReport

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Run :android Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger
