name: iOS - Lint and Test

on:
  pull_request:
    types: [ opened, reopened, edited, synchronize, ready_for_review ]

defaults:
  run:
    working-directory: ios

jobs:
  lint_and_test:
    name: Pull request review for iOS
    runs-on: macos-13
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Konfig Properties
        env:
          BUILD_KONFIG: ${{ secrets.BUILD_KONFIG }}
        run: |
          cd ..
          echo "$BUILD_KONFIG" > buildSrc/src/main/kotlin/appPackage/BuildKonfig.kt
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Generate KMM frameworks for Cocoapods
        run: |
          cd ..
          ./gradlew generateDummyFramework
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Bundle install
        run: bundle install

      - name: Cache Pods
        uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install Pods Dependencies
        run: bundle exec pod install

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0-beta'

      - name: Lint
        run: ./Pods/SwiftLint/swiftlint

      - name: Build and Test
        run: bundle exec fastlane build_and_test
        env:
          CI: true
